version: "3"
services:
  server:
    image: schlump:geoserver
    ports:
      - "8080:8080"
    networks:
      - spatialnet
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  db:
    image: schlump:postgis
    ports:
      - "5432"
    networks:
      - spatialnet
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  web:
    image: schlump:mapbender
    ports:
      - "80:80"
    networks:
      - spatialnet
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        
networks:
  spatialnet:
  databse:
